---
title: "Making a covariance matrix from data"
author: "Hussein Al-Asadi"
date: 2015-12-28
---

**Last updated:** `r Sys.Date()`

**Code version:** `r system("git log -1 --format='%H'", intern = TRUE)`

```{r chunk-options, include=FALSE}
rm(list=ls())
source("chunk-options.R")
```

```{r wrangle}
# wrangle data
d <- read.table("../data/european_blocks/chr2/2_135158578_137042794.impute.hap", header = F, stringsAsFactors = FALSE)
snplist <- read.table("../data/european_blocks/chr2/2_135158578_137042794.impute.legend", header=T, stringsAsFactors = FALSE)
# X: n x p genotype matrix
X <- t(as.matrix(d))

rmb_map <- read.table("../data/map/chr2.interpolated_genetic_map", header = F, stringsAsFactors = FALSE)
my_matches <- match(snplist$ID, rmb_map$V1)
exl_snps <- which(is.na(my_matches))
X <- X[,-exl_snps]
freq <- colMeans(X)
names(freq) <- snplist$ID[-exl_snps]
cummap <- rmb_map$V3[which(!is.na(my_matches))]
positions <- rmb_map$V2[which(!is.na(my_matches))]
```

```{r shrink_cov}
shrink_cov <- function(Ne, cummap, Xpanel){
  # USAGE: compute the shrinkage estimator of covariance matrix in Wen and Stephens (2010)
  #INPUT:
  #    Ne: the effective population size (diploid)
  #    cummap: cumulative genetic map in cM
  #    Xpanel: phased genotype panel, numIND by numSNP
  #OUTPUT:
  #    SigHat: estimated covariance matrix of haplotype, numSNP by numSNP

    # theta is related to mutation
  
    # we have haploid data
    numIND = nrow(Xpanel)/2
    numSNP = ncol(Xpanel)

    nsum = sum(1 / (1:(2*numIND-1)));
    theta = (1/nsum) / (2*numIND + 1/nsum);
    
    # S is obtained from Sigma_panel by shrinking off-diagonal entries toward 0
    # NB: Xpanel is phased genotype panel data; 
    S <- ((2*numIND-1)/(2*numIND)) * cov(Xpanel);
    
    for (i in 1:numSNP){
      for (j in 1:numSNP){
        rho = 4 * Ne * (abs(cummap[j] - cummap[i])) / 100;
        shrinkage = exp(-rho/(2*numIND));
        # hard thresholding to obtain sparse and banded estimator
        if (shrinkage < 1e-8){
          shrinkage = 0;
        }
        if (i != j){
          S[i,j] = shrinkage * S[i, j];
        }
      }
    }
    
    # derived from Li and Stephens model (2003)
    SigHat = (1-theta)^2 * S + 0.5*theta * (1-0.5*theta) * diag(1, numSNP);
    return(SigHat)
}


```


```{r execution}
# finally shrink the covariance matrix
Sighat <- shrink_cov(10000, cummap, X)
save(Sighat, file = "../data/european_blocks/chr2/2_135158578_137042794.cov.Rdata")
save(freq, file = "../data/european_blocks/chr2/2_135158578_137042794.freq.Rdata")
p <- dim(Sighat)[1]
bins <- cut(1:p, 10)
plot(tapply(Sighat[6,], bins, mean))
plot(Sighat[6,])

plot(tapply(Sighat[600,], bins, mean))
plot(Sighat[600,])
```

## Session information

```{r info}
sessionInfo()
```
